'use client';
import './globals.css';
import { RecoilRoot } from 'recoil';

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<title>SKY LAB Bilgisayar Bilimleri Kulübü</title>
				<link rel='shortcut icon' href='favicon.png' type='image/x-icon' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='true'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap'
					rel='stylesheet'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body>
				<RecoilRoot>{children}</RecoilRoot>
			</body>
		</html>
	);
}
